title:              miintto.log
email:              miintto.log@gmail.com
description:        미민또의 프로그래밍
author:             miintto
baseurl:            ""
url:                "https://miintto.github.io"

# Social Profiles
twitter_username:
github_username:    miintto
facebook_username:
instagram_username: miintto.log
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
permalink:          "/docs/:title"
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc
